/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEMA_H_RPCGEN
#define _TEMA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct access_response {
	char *access_token;
	char *refresh_token;
	int ttl;
};
typedef struct access_response access_response;

struct access_request {
	char *id;
	char *auth_token;
	int generate_refresh_token;
};
typedef struct access_request access_request;

struct action {
	char *op;
	char *resource;
	char *acces_token;
};
typedef struct action action;

#define TEMAPROG 0x32345678
#define TEMAVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define REQUEST_AUTHORIZATION 1
extern  char ** request_authorization_1(char **, CLIENT *);
extern  char ** request_authorization_1_svc(char **, struct svc_req *);
#define REQUEST_ACCES_TOKEN 2
extern  access_response * request_acces_token_1(access_request *, CLIENT *);
extern  access_response * request_acces_token_1_svc(access_request *, struct svc_req *);
#define VALIDATE_DELEGATED_ACTION 3
extern  char ** validate_delegated_action_1(action *, CLIENT *);
extern  char ** validate_delegated_action_1_svc(action *, struct svc_req *);
#define APPROVE_REQUEST_TOKEN 4
extern  char ** approve_request_token_1(char **, CLIENT *);
extern  char ** approve_request_token_1_svc(char **, struct svc_req *);
extern int temaprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REQUEST_AUTHORIZATION 1
extern  char ** request_authorization_1();
extern  char ** request_authorization_1_svc();
#define REQUEST_ACCES_TOKEN 2
extern  access_response * request_acces_token_1();
extern  access_response * request_acces_token_1_svc();
#define VALIDATE_DELEGATED_ACTION 3
extern  char ** validate_delegated_action_1();
extern  char ** validate_delegated_action_1_svc();
#define APPROVE_REQUEST_TOKEN 4
extern  char ** approve_request_token_1();
extern  char ** approve_request_token_1_svc();
extern int temaprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_access_response (XDR *, access_response*);
extern  bool_t xdr_access_request (XDR *, access_request*);
extern  bool_t xdr_action (XDR *, action*);

#else /* K&R C */
extern bool_t xdr_access_response ();
extern bool_t xdr_access_request ();
extern bool_t xdr_action ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEMA_H_RPCGEN */
