/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tema.h"
#include <vector>
#include <iostream>
#include <fstream>
#include <string>
#include <map>

using namespace std;

// userid - < access token, refresh_token, ttl >
map<string, access_response> userid_access_tokens;

void make_request_access(access_request  *request_access, CLIENT *clnt, char *user, char **auth_token) {
	access_response  *request_access_response;


	// Am primit tokenul de autorizare de la utilizator (semnat sau nu)
	request_access_response = request_acces_token_1(request_access, clnt);
	if (request_access_response == (access_response *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	// Am primit ACCESS
	if(strcmp(request_access_response->access_token, "REQUEST_DENIED")) {
		auto userid_access_entry = userid_access_tokens.find(user);
		// Verific daca exista deja un access token pentru acest user
		if (userid_access_entry == userid_access_tokens.end()) {
			// Nu exista
			userid_access_tokens.insert({user, *request_access_response});
		} else {
			userid_access_entry->second = *request_access_response;
		}

		// Daca la request access nu folosesc tokenul de autentificare (folosesc pe cel de refresh)
		//  e cerere de refresh si nu printez
		if (auth_token != NULL) {
			printf("%s -> %s", *auth_token,request_access_response->access_token);
			if (request_access->generate_refresh_token) {
				printf(",%s", request_access_response->refresh_token);
			}
			printf("\n");
		}
		
	} else {
		printf("REQUEST_DENIED\n");
	}
}

void make_request(char *user, CLIENT *clnt, int generate_refresh_token) {
	char * *auth_token;
	char * *signed_token;
	access_response  *request_access_response;
	access_request  request_access;


	auth_token = request_authorization_1(&user, clnt);
	if (auth_token == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	if (strcmp(*auth_token, "USER_NOT_FOUND")) {
		// Facem cererea de aprobare 
		signed_token = approve_request_token_1(auth_token, clnt);
		if (signed_token == (char **) NULL) {
			clnt_perror (clnt, "call failed");
		}
		// dupa aprobare, fac cerere de acces
		request_access.id = strdup(user);
		request_access.auth_token = strdup(*signed_token);
		request_access.generate_refresh_token = generate_refresh_token;
		make_request_access(&request_access, clnt, user, auth_token);
	} else {
		printf("USER_NOT_FOUND\n");
	}
}

void
temaprog_1(char *host, char *fd_op)
{
	CLIENT *clnt;
	char **auth_token;
	access_response  *request_access_response;
	access_request  request_access;
	char **resource_server_response;
	action_request  resource_request_params;
	char **signed_token;

#ifndef	DEBUG
	clnt = clnt_create (host, TEMAPROG, TEMAVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	string line, op;
	char *user;
	char *ptr;
	char *value;
	ifstream fd_operatii(fd_op);
	if (fd_operatii.is_open()) {
		while(getline(fd_operatii, line)) {
			ptr = strtok((char *)line.c_str(), ",");
			user = ptr;
			op = strtok(NULL, ",");
			value = strtok(NULL,",");

			if (!op.compare("REQUEST")) { // Avem REQUEST
				make_request(user, clnt, atoi(value));
			} else { // Avem cerere de resursa
				auto found = userid_access_tokens.find(user);
				if (found != userid_access_tokens.end()) {
					// daca expira token-ul si are refresh token nenul
					if (found->second.ttl == 0 && strcmp(found->second.refresh_token,"")) {
						request_access.id = strdup(user);
						request_access.auth_token = strdup(found->second.refresh_token);
						request_access.generate_refresh_token = 1;
						make_request_access(&request_access, clnt, user, NULL);
					}

					resource_request_params.acces_token = (char*)userid_access_tokens.find(user)->second.access_token;
				} else {
					resource_request_params.acces_token = strdup("");
				}
				resource_request_params.op = (char *)op.c_str();
				resource_request_params.resource = (char *)value;

				resource_server_response = validate_delegated_action_1(&resource_request_params, clnt);
				if (resource_server_response == (char **) NULL) {
					clnt_perror (clnt, "call failed");
				}
				printf("%s\n", *resource_server_response);
				if (strcmp(*resource_server_response, "PERMISSION_DENIED") && userid_access_tokens.find(user) != userid_access_tokens.end()) {
					userid_access_tokens.find(user)->second.ttl--;
				}
			}
		}
	}



#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	temaprog_1 (host, argv[2]);
exit (0);
}
